name: CI/CD Shopify Theme

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to Shopify
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Shopify CLI
              run: npm install -g @shopify/cli @shopify/theme

            - name: Deploy to Shopify
              env:
                  SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
                  SHOPIFY_ADMIN_API_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
              run: |
                  shopify theme push --store ${SHOPIFY_STORE_URL} --password ${SHOPIFY_ADMIN_API_TOKEN} --theme-id 179739263325
